//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `Proto.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include "../include/Proto.h"
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 8
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_GoKu_InterfaceEval_ids[2] =
{
    "::GoKu::InterfaceEval",
    "::Ice::Object"
};
const ::std::string iceC_GoKu_InterfaceEval_ops[] =
{
    "evaluate",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_GoKu_InterfaceEval_evaluate_name = "evaluate";

}

bool
GoKu::InterfaceEval::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_GoKu_InterfaceEval_ids, iceC_GoKu_InterfaceEval_ids + 2, s);
}

::std::vector<::std::string>
GoKu::InterfaceEval::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_GoKu_InterfaceEval_ids[0], &iceC_GoKu_InterfaceEval_ids[2]);
}

::std::string
GoKu::InterfaceEval::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
GoKu::InterfaceEval::ice_staticId()
{
    static const ::std::string typeId = "::GoKu::InterfaceEval";
    return typeId;
}

/// \cond INTERNAL
bool
GoKu::InterfaceEval::_iceD_evaluate(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Idempotent, current.mode);
    auto istr = inS.startReadParams();
    RequestBatch iceP_req;
    istr->readAll(iceP_req);
    inS.endReadParams();
    ReplyBatch iceP_rep;
    this->evaluate(::std::move(iceP_req), iceP_rep, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_rep);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
GoKu::InterfaceEval::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_GoKu_InterfaceEval_ops, iceC_GoKu_InterfaceEval_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_GoKu_InterfaceEval_ops)
    {
        case 0:
        {
            return _iceD_evaluate(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
GoKu::InterfaceEvalPrx::_iceI_evaluate(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::GoKu::ReplyBatch>>& outAsync, const RequestBatch& iceP_req, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_GoKu_InterfaceEval_evaluate_name);
    outAsync->invoke(iceC_GoKu_InterfaceEval_evaluate_name, ::Ice::OperationMode::Idempotent, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_req);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
GoKu::InterfaceEvalPrx::_newInstance() const
{
    return ::IceInternal::createProxy<InterfaceEvalPrx>();
}
/// \endcond

const ::std::string&
GoKu::InterfaceEvalPrx::ice_staticId()
{
    return InterfaceEval::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_GoKu_InterfaceEval_evaluate_name = "evaluate";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::GoKu::upCast(InterfaceEval* p) { return p; }

void
::IceProxy::GoKu::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< InterfaceEval>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new InterfaceEval;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::GoKu::InterfaceEval::_iceI_begin_evaluate(const ::GoKu::RequestBatch& iceP_req, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_GoKu_InterfaceEval_evaluate_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_GoKu_InterfaceEval_evaluate_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_GoKu_InterfaceEval_evaluate_name, ::Ice::Idempotent, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_req);
        result->endWriteParams();
        result->invoke(iceC_GoKu_InterfaceEval_evaluate_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::GoKu::InterfaceEval::end_evaluate(::GoKu::ReplyBatch& iceP_rep, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_GoKu_InterfaceEval_evaluate_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_rep);
    result->_endReadParams();
}

void IceProxy::GoKu::InterfaceEval::_iceI_end_evaluate(::GoKu::ReplyBatch& iceP_rep, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_GoKu_InterfaceEval_evaluate_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_rep);
    result->_endReadParams();
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::GoKu::InterfaceEval::_newInstance() const
{
    return new InterfaceEval;
}
/// \endcond

const ::std::string&
IceProxy::GoKu::InterfaceEval::ice_staticId()
{
    return ::GoKu::InterfaceEval::ice_staticId();
}

GoKu::InterfaceEval::~InterfaceEval()
{
}

/// \cond INTERNAL
::Ice::Object* GoKu::upCast(InterfaceEval* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_GoKu_InterfaceEval_ids[2] =
{
    "::GoKu::InterfaceEval",
    "::Ice::Object"
};

}

bool
GoKu::InterfaceEval::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_GoKu_InterfaceEval_ids, iceC_GoKu_InterfaceEval_ids + 2, s);
}

::std::vector< ::std::string>
GoKu::InterfaceEval::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_GoKu_InterfaceEval_ids[0], &iceC_GoKu_InterfaceEval_ids[2]);
}

const ::std::string&
GoKu::InterfaceEval::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
GoKu::InterfaceEval::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::GoKu::InterfaceEval";
    return typeId;
#else
    return iceC_GoKu_InterfaceEval_ids[0];
#endif
}

/// \cond INTERNAL
bool
GoKu::InterfaceEval::_iceD_evaluate(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Idempotent, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    RequestBatch iceP_req;
    istr->read(iceP_req);
    inS.endReadParams();
    ReplyBatch iceP_rep;
    this->evaluate(iceP_req, iceP_rep, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_rep);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_GoKu_InterfaceEval_all[] =
{
    "evaluate",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
GoKu::InterfaceEval::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_GoKu_InterfaceEval_all, iceC_GoKu_InterfaceEval_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_GoKu_InterfaceEval_all)
    {
        case 0:
        {
            return _iceD_evaluate(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
GoKu::InterfaceEval::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< InterfaceEval, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
GoKu::InterfaceEval::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< InterfaceEval, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
GoKu::_icePatchObjectPtr(InterfaceEvalPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = InterfaceEvalPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(InterfaceEval::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
